<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function listAllPageCategories() {
        $query = $this->getEntityManager()
                ->createQueryBuilder()->select("c")
                ->from("AppBundle:Category", "c")
                ->orderBy("c.title", "ASC");

        $paginator = new Paginator($query, $fetchJoinCollection = false);

        $c = count($paginator);
        $categoryData = [];

        foreach ($paginator as $category) {
            $categoryData[] = $category;
        }
        return [
            "records" => $categoryData,
            "recordsCount" => $c
        ];
    }

    public function listActivePageCategories() {
        $query = $this->getEntityManager()
                ->createQueryBuilder()->select("c")
                ->from("AppBundle:Category", "c")
                ->where("c.status = 1")
                ->orderBy("c.title", "ASC")
                ->getQuery();

        return $query->getResult();
    }

    public function categoryDetail($slug) {

        $query = $this->getEntityManager()
                ->createQueryBuilder()->select("c")
                ->from("AppBundle:Category", "c")
                ->where("c.slug = ?1 AND c.status = 1")
                ->setParameter(1, $slug)
                ->getQuery();

        $categoryDetails = $query->getSingleResult();

        return $categoryDetails;
    }

}
