<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function listAllPageCategories()
    {
        $query = $this->getEntityManager()
                ->createQueryBuilder()->select("c")
                ->from("AppBundle:Category","c")
                ->orderBy("c.title", "ASC");
        
        $paginator = new Paginator($query, $fetchJoinCollection = false);

        $c = count($paginator);
        $categoryData = [];

        foreach ($paginator as $category) {
            $categoryData[] = $category;
        }
        return [
            "records" => $categoryData,
            "recordsCount" => $c
        ];
    }
}
